spring:
  application:
    name: l9g-accountinfo
  profiles:
    active: default
  config:
    import: optional:file:data/config.yaml
  banner:
    location: classpath:banner.txt

  messages:
    basename: messages
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          app:
            client-id: nix
            client-secret: "*** not set ***"
            scope: openid,profile,email,roles
        provider:
          app:
            issuer-uri: https://id.dev.sonia.de/realms/dev
            user-name-attribute: preferred_username

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger:%line - %yellow(%msg %n)"
  level:
    root: INFO
    com.zaxxer.hikari.pool.HikariPool: ERROR
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.hibernate.orm.connections.pooling: ERROR

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 9h
  forward-headers-strategy: framework
  
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: NEVER

springdoc:
  show-actuator: false
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  development: false
  javascript:
    log-level: info
  oauth2:
    registration-id: app
    client-id: accountinfo
  resource-access-roles: accountinfo
  default:
    locale: en
  base-url: http://localhost:8080
  ws-url: ws://localhost:8080
  storage-location: "./data/secrets"
